INFO:root:Current server time: 2024-05-06 17:34:37.217308
INFO:root:Current server time: 2024-05-06 17:57:19.967031
INFO:root:Current server time: 2024-05-06 17:57:44.415931
INFO:django.utils.autoreload:/Users/huy/code/project/app/tasks.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:Current server time: 2024-05-06 18:00:10.796812
INFO:root:Current server time: 2024-05-06 18:00:32.785704
INFO:root:Current server time: 2024-05-06 18:01:23.555875
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:Current server time: 2024-05-07 09:58:07.495501
WARNING:django.request:Not Found: /favicon.ico
INFO:root:Current server time: 2024-05-07 09:58:21.929730
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/admin.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:Current server time: 2024-05-07 11:55:33.234766
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:Current server time: 2024-05-07 13:50:03.314529
INFO:root:Current server time: 2024-05-07 13:50:03.345974
INFO:django.utils.autoreload:/Users/huy/code/project/app/settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/app/settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/app/settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/app/settings.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Bad Request: /api/comments/
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
ERROR:django.request:Internal Server Error: /api/comments/
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/mixins.py", line 17, in create
    serializer = self.get_serializer(data=request.data)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'CommentViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
ERROR:django.request:Internal Server Error: /api/comments/
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/mixins.py", line 17, in create
    serializer = self.get_serializer(data=request.data)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'CommentViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/serializers.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/serializers.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Bad Request: /api/comments/
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/serializers.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/serializers.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/serializers.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
ERROR:django.request:Internal Server Error: /api/comments/
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 223, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 442, in run_validation
    value = self.to_internal_value(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 501, in to_internal_value
    validated_value = validate_method(validated_value)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/catalog/serializers.py", line 33, in validate_comment
    if value.len() < 5:
       ^^^^^^^^^
AttributeError: 'str' object has no attribute 'len'
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/serializers.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
ERROR:django.request:Internal Server Error: /api/comments/
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 223, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 442, in run_validation
    value = self.to_internal_value(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 501, in to_internal_value
    validated_value = validate_method(validated_value)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/catalog/serializers.py", line 33, in validate_comment
    if len(value) < 5:
       ^^^^^^^^^
AttributeError: 'str' object has no attribute 'len'
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/serializers.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Bad Request: /api/comments/
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/serializers.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Bad Request: /api/comments/
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Bad Request: /api/comments/
WARNING:django.request:Bad Request: /api/comments/
WARNING:django.request:Bad Request: /api/comments/
WARNING:django.request:Bad Request: /api/comments/
WARNING:django.request:Bad Request: /api/comments/
WARNING:django.request:Bad Request: /api/comments/
WARNING:django.request:Bad Request: /api/comments/
WARNING:django.request:Bad Request: /api/comments/
WARNING:django.request:Bad Request: /api/comments/
WARNING:django.request:Bad Request: /api/comments/
WARNING:django.request:Bad Request: /api/comments/
WARNING:django.request:Bad Request: /api/comments/
WARNING:django.request:Bad Request: /api/comments/
WARNING:django.request:Bad Request: /api/comments/
WARNING:django.request:Bad Request: /api/comments/
WARNING:django.request:Bad Request: /api/comments/
WARNING:django.request:Bad Request: /api/comments/
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:Current server time: 2024-05-07 16:26:45.803506
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
ERROR:django.request:Internal Server Error: /catalog/products/2/
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/engine.py", line 204, in select_template
    raise TemplateDoesNotExist("No template names provided")
django.template.exceptions.TemplateDoesNotExist: No template names provided

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/catalog/views.py", line 103, in product_detail
    return render(request, 'products/product_view.html', {'product': product})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: No template names provided
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Bad Request: /api/comments/
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/models.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:root:Current server time: 2024-05-07 17:03:23.633623
WARNING:drf_yasg.inspectors.base:view's ReportViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
           ^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'ReportViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
WARNING:drf_yasg.inspectors.base:view's ReportViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
           ^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'ReportViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
WARNING:drf_yasg.inspectors.base:view's ReportViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
           ^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'ReportViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
WARNING:drf_yasg.inspectors.base:view's ReportViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
           ^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'ReportViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
WARNING:drf_yasg.inspectors.base:view's ReportViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
           ^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'ReportViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
WARNING:drf_yasg.inspectors.base:view's ReportViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
           ^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'ReportViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:drf_yasg.inspectors.base:view's ReportViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
           ^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'ReportViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
WARNING:drf_yasg.inspectors.base:view's ReportViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
           ^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'ReportViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
WARNING:drf_yasg.inspectors.base:view's ReportViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
           ^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'ReportViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/views.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:drf_yasg.inspectors.base:view's ReportViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
           ^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'ReportViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
WARNING:drf_yasg.inspectors.base:view's ReportViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
           ^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'ReportViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
WARNING:drf_yasg.inspectors.base:view's ReportViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
           ^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'ReportViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
WARNING:drf_yasg.inspectors.base:view's ReportViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
           ^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'ReportViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
WARNING:drf_yasg.inspectors.base:view's ReportViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
           ^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'ReportViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
WARNING:drf_yasg.inspectors.base:view's ReportViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
           ^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'ReportViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/serializers.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/serializers.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:drf_yasg.inspectors.base:view's ReportViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
           ^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'ReportViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
WARNING:drf_yasg.inspectors.base:view's ReportViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
           ^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'ReportViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
WARNING:drf_yasg.inspectors.base:view's ReportViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
           ^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'ReportViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
WARNING:drf_yasg.inspectors.base:view's ReportViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
           ^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'ReportViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
WARNING:drf_yasg.inspectors.base:view's ReportViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
           ^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'ReportViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
WARNING:drf_yasg.inspectors.base:view's ReportViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
           ^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'ReportViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
WARNING:drf_yasg.inspectors.base:view's ReportViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
           ^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'ReportViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
WARNING:drf_yasg.inspectors.base:view's ReportViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
           ^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'ReportViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
WARNING:drf_yasg.inspectors.base:view's ReportViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
           ^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'ReportViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /api/comments/32/add_reply_comments/
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
INFO:django.utils.autoreload:/Users/huy/code/project/catalog/serializers.py changed, reloading.
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/path_to_profile_picture
WARNING:django.request:Not Found: /catalog/products/2/{% static }
WARNING:django.request:Not Found: /catalog/products/2/{% static }
WARNING:django.request:Not Found: /catalog/products/2/{% static }
WARNING:django.request:Not Found: /catalog/products/2/{% static }
WARNING:django.request:Not Found: /catalog/products/2/{% static 'images/ava1.jpg'}
WARNING:django.request:Not Found: /catalog/products/2/{% static 'images/ava1.jpg'}
WARNING:django.request:Not Found: /catalog/products/2/{% static 'images/ava1.jpg'}
WARNING:django.request:Not Found: /catalog/products/2/{% static 'images/ava1.jpg'}
WARNING:django.request:Not Found: /catalog/products/2/{% static 'images/ava1.jpg'}
WARNING:django.request:Not Found: /catalog/products/2/{% static 'images/ava1.jpg'}
WARNING:django.request:Not Found: /catalog/products/2/{% static 'images/ava1.jpg'}
WARNING:django.request:Not Found: /catalog/products/2/{% static 'images/ava1.jpg'}
WARNING:django.request:Not Found: /catalog/products/2/{% static 'images/ava1.jpg'}
WARNING:django.request:Not Found: /catalog/products/2/{% static 'images/ava1.jpg'}
WARNING:django.request:Not Found: /catalog/products/2/{% static 'images/ava1.jpg'}
WARNING:django.request:Not Found: /catalog/products/2/{% static 'images/ava1.jpg'}
ERROR:django.request:Internal Server Error: /catalog/products/2/
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/catalog/views.py", line 113, in product_detail
    return render(request, 'products/product_view.html', {'product': product})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 44: 'static', expected 'endblock'. Did you forget to register or load this tag?
ERROR:django.request:Internal Server Error: /catalog/products/2/
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/catalog/views.py", line 113, in product_detail
    return render(request, 'products/product_view.html', {'product': product})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/template/base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 44: 'static', expected 'endblock'. Did you forget to register or load this tag?
INFO:django.utils.autoreload:Watching for file changes with StatReloader
ERROR:django.request:Internal Server Error: /api/comments/33/add_reply_comment/
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.NotNullViolation: null value in column "name" of relation "catalog_reply" violates not-null constraint
DETAIL:  Failing row contains (13, 2024-05-07 11:07:51.662685+00, 2024-05-07 11:07:51.66272+00, null, null, 33).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/catalog/views.py", line 33, in add_reply_comment
    reply = Reply.objects.create(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/db/models/base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/db/models/base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/db/models/base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: null value in column "name" of relation "catalog_reply" violates not-null constraint
DETAIL:  Failing row contains (13, 2024-05-07 11:07:51.662685+00, 2024-05-07 11:07:51.66272+00, null, null, 33).

INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /favicon.ico
INFO:root:Current server time: 2024-05-08 08:56:13.148913
WARNING:drf_yasg.inspectors.base:view's ReportViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
           ^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'ReportViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
WARNING:drf_yasg.inspectors.base:view's ReportViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
           ^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'ReportViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
WARNING:drf_yasg.inspectors.base:view's ReportViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
           ^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huy/code/project/.venv/lib/python3.12/site-packages/rest_framework/generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'ReportViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
